version: "3"

services:
  transaction_api:
    build:
      context: ${PWD}
      dockerfile: ./docker/Dockerfile
    image: nelsonlpco/transaction:prod
    container_name: transactionapi
    ports: 
      - 5566:5566
    environment:
      - SERVER_PORT=5566
      - SQL_DRIVER=mysql
      - CONNECTION_STRING=root:admin@tcp(mysql:3306)/transactions?multiStatements=true
      - LOG_LEVEL=5
      - TTL=3
      - CONNECTION_TIMEOUT=60
      - SCHEMAS_PATH=/go/bin/v1_schema.sql
    command: -d -s
    depends_on:
      - mysql
    networks:
      - transaction-api

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports: 
      - "8081:8080"
    volumes: 
      - ${PWD}/doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml
    depends_on:
      - transaction_api
    networks:
      - transaction-api

  mysql:
    platform: linux/amd64
    image: mysql
    container_name: transactions_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=transactions
    # volumes:
      # - ./data/mysql:/var/lib/mysql
    networks:
      - transaction-api

networks:
  transaction-api:
    driver: bridge