openapi: 3.0.0

info:
  title: Transactions api
  description: Make Transactions by customer account
  version: 1.0.0

servers:
  - url: http://localhost:5566
    description: localhost server

paths:
  /accounts:
    post:
      summary: Creates a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/account' 
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    example: 201
                  message:
                    type: object
                    properties:
                      AccountId: 
                        type: string
                        example: be800017-343c-4191-89ad-426eb512437f
                
        '400':
          description: An bad request send to service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequestError'
        '500':
          description: A internal server error ocurred 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'


  /accounts/{accountId}:
    get:
      summary: returns an account by accountId
      parameters:
        - name: accountId
          in: path
          required: true
          description: account id
          schema:
            type: string
            format: uuid
            example: 123e4567-e89b-12d3-a456-426655440000
      responses:
        '200':
          description: An account object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account' 
        '204':
          description: Account not found, not content
        '400':
          description: An bad request send to service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequestError'
        '500':
          description: A internal server error ocurred 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
  /transactions:
    post:
      summary: Creates an new transaction type 
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/transaction' 
      responses:
        '201':
          description: Created
        '400':
          description: An bad request send to service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/badRequestError'
        '500':
          description: A internal server error ocurred 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'

components:
  schemas:
    account:
      type: object
      properties:
        statusCode: 
          type: number
          example: 200
        data:
          type: object
          properties:
            id: 
              type: string
              format: uuid
              example: 123e4567-e89b-12d3-a456-426655440000
            documentNumber:
              type: string
              example: 48461422481
    transaction:
      type: object
      properties:
        operationTypeId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
        accountId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
        amount:
          type: number
          format: float64
          example: 23.254
    badRequestError:
      type: object
      properties:
        errorCode:
          type: number
          format: int
          example: 400
        errorMessage:
          type: string
          example: Bad Operation
    internalServerError:
      type: object
      properties:
        errorCode:
          type: number
          format: int
          example: 500
        errorMessage:
          type: string
          example: Error

